#!/bin/bash

ZSH_CUSTOM=~/.oh-my-zsh/custom

cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

echo "Install system packages"
# Tools.
sudo apt install -y vim zsh tmux direnv
# Apps.
sudo apt install -y thefuck ranger
# Quick Python setup.
sudo apt install -y python3-dev python3-pip python3-venv

echo "Install python packages"
pip3 install --user --upgrade pip

python3 -m pip install --user pipx black
python3 -m pipx ensurepath
pipx install black
