#!/bin/bash

ZSH_CUSTOM=~/.oh-my-zsh/custom

cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

echo "Install system packages"
sudo apt install vim zsh tmux python-dev python3-dev python-pip python3-pip direnv 

echo "Install python packages"
pip install --user pip
pip3 install --user pip
