#!/bin/bash

ZSH_CUSTOM=~/.oh-my-zsh/custom

cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

echo "Install system packages"
# Tools.
sudo apt install -y vim zsh tmux direnv
# Apps.
sudo apt install -y thefuck ranger 
# Quick Python setup.
sudo apt install -y python-dev python3-dev python-pip python3-pip python3-venv

echo "Install python packages"
pip install --user --upgrade pip
pip3 install --user --upgrade pip

pip3 install --user --upgrade pipsi
pipsi install jupytext
pipsi install nbdime 
